DancingGoatMvc/Models/Checkout/AddressSelectorViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace DancingGoat.Models.Checkout
{
    public class AddressSelectorViewModel
    {
        [Display(Name = "DancingGoatMvc.Address")]
        public int? AddressID { get; set; }
        

        public SelectList Addresses { get; set; }


        public bool HasSomeAddress => (Addresses != null) && Addresses.Any();
    }
}

DancingGoatMvc/Models/Checkout/BillingAddressViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

using CMS.Ecommerce;
using CMS.Globalization;

namespace DancingGoat.Models.Checkout
{
    [Bind(Exclude = "Countries")]
    public class BillingAddressViewModel
    {
        [Required]
        [Display(Name = "DancingGoatMvc.Address.Line1")]
        [MaxLength(100, ErrorMessage = "General.MaxlengthExceeded")]
        public string BillingAddressLine1 { get; set; }



        [Display(Name = "DancingGoatMvc.Address.Line2")]
        [MaxLength(100, ErrorMessage = "General.MaxlengthExceeded")]
        public string BillingAddressLine2 { get; set; }


        [Required]
        [Display(Name = "DancingGoatMvc.Address.City")]
        [MaxLength(100, ErrorMessage = "General.MaxlengthExceeded")]
        public string BillingAddressCity { get; set; }


        [Required]
        [Display(Name = "DancingGoatMvc.Address.Zip")]
        [MaxLength(20, ErrorMessage = "General.MaxlengthExceeded")]
        public string BillingAddressPostalCode { get; set; }
        

        public CountryStateViewModel BillingAddressCountryStateSelector { get; set; }


        public AddressSelectorViewModel BillingAddressSelector { get; set; }


        public SelectList Countries { get; set; }


        public string BillingAddressState { get; set; }


        public string BillingAddressCountry { get; set; }


        public BillingAddressViewModel()
        {
        }


        public BillingAddressViewModel(AddressInfo address, SelectList countries, SelectList addresses = null)
        {
            if (address != null)
            {
                BillingAddressLine1 = address.AddressLine1;
                BillingAddressLine2 = address.AddressLine2;
                BillingAddressCity = address.AddressCity;
                BillingAddressPostalCode = address.AddressZip;
                BillingAddressState = StateInfoProvider.GetStateInfo(address.AddressStateID)?.StateDisplayName ?? String.Empty;
                BillingAddressCountry = CountryInfoProvider.GetCountryInfo(address.AddressCountryID)?.CountryDisplayName ?? String.Empty;
                Countries = countries;
            }

            BillingAddressCountryStateSelector = new CountryStateViewModel
            {
                Countries = countries,
                CountryID = address?.AddressCountryID ?? 0,
                StateID = address?.AddressStateID ?? 0
            };

            BillingAddressSelector = new AddressSelectorViewModel
            {
                Addresses = addresses,
                AddressID = address?.AddressID ?? 0
            };
        }


        public void ApplyTo(AddressInfo address)
        {
            address.AddressLine1 = BillingAddressLine1;
            address.AddressLine2 = BillingAddressLine2;
            address.AddressCity = BillingAddressCity;
            address.AddressZip = BillingAddressPostalCode;
            address.AddressCountryID = BillingAddressCountryStateSelector.CountryID;
            address.AddressStateID = BillingAddressCountryStateSelector.StateID ?? 0;
        }
    }
}

DancingGoatMvc/Models/Checkout/CouponCodesUpdateModel.cs
using System.ComponentModel.DataAnnotations;

namespace DancingGoat.Models.Checkout
{
    public class CouponCodesUpdateModel
    {
        [MaxLength(200, ErrorMessage = "General.MaxlengthExceeded")]
        public string NewCouponCode { get; set; }


        public string RemoveCouponCode { get; set; }
    }
}

DancingGoatMvc/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using CMS.Base;
using CMS.Ecommerce;
using CMS.Helpers;

using DancingGoat.ActionSelectors;
using DancingGoat.Models.Checkout;
using DancingGoat.Repositories;
using DancingGoat.Services;

namespace DancingGoat.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IShoppingService mShoppingService;
        private readonly ICheckoutService mCheckoutService;
        private readonly IContactRepository mContactRepository;
        private readonly IProductRepository mProductRepository;


        public CheckoutController(IShoppingService shoppingService, IContactRepository contactRepository, IProductRepository productRepository, ICheckoutService checkoutService)
        {
            mShoppingService = shoppingService;
            mContactRepository = contactRepository;
            mCheckoutService = checkoutService;
            mProductRepository = productRepository;
        }


        public ActionResult ShoppingCart()
        {
            var viewModel = mCheckoutService.PrepareCartViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult ShoppingCartCheckout()
        {
            var cart = mShoppingService.GetCurrentShoppingCart();
            var validationErrors = ShoppingCartInfoProvider.ValidateShoppingCart(cart);

            cart.Evaluate();

            if (!validationErrors.Any())
            {
                var customer = GetCustomerOrCreateFromAuthenticatedUser();
                if (customer != null)
                {
                    mShoppingService.SetCustomer(customer);
                }

                mShoppingService.SaveCart();
                return RedirectToAction("DeliveryDetails");
            }

            // Fill model state with errors from the check result
            ProcessCheckResult(validationErrors);

            var viewModel = mCheckoutService.PrepareCartViewModel();

            return View("ShoppingCart", viewModel);
        }


        public ActionResult DeliveryDetails()
        {
            var cart = mShoppingService.GetCurrentShoppingCart();
            if (cart.IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = mCheckoutService.PrepareDeliveryDetailsViewModel();

            return View(viewModel);
        }


        public ActionResult PreviewAndPay()
        {
            if (mShoppingService.GetCurrentShoppingCart().IsEmpty)
            {
                return RedirectToAction("ShoppingCart");
            }

            var viewModel = mCheckoutService.PreparePreviewViewModel();

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreviewAndPay(PreviewViewModel model)
        {
            var cart = mShoppingService.GetCurrentShoppingCart();

            if (cart.IsEmpty)
            {
                ModelState.AddModelError("cart.empty", ResHelper.GetString("DancingGoatMvc.Checkout.EmptyCartError"));

                var viewModel = mCheckoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            if (!mCheckoutService.IsPaymentMethodValid(model.PaymentMethod.PaymentMethodID))
            {
                ModelState.AddModelError("PaymentMethod.PaymentMethodID", ResHelper.GetString("DancingGoatMvc.Payment.PaymentMethodRequired"));
            }
            else
            {
                mShoppingService.SetPaymentOption(model.PaymentMethod.PaymentMethodID);
            }

            var validator = new CreateOrderValidator(cart);

            if (!validator.Validate())
            {
                ProcessCheckResult(validator.Errors);
            }

            if (!ModelState.IsValid)
            {
                var viewModel = mCheckoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            try
            {
                mShoppingService.CreateOrder();
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("cart.createordererror", ex.Message);
                var viewModel = mCheckoutService.PreparePreviewViewModel(model.PaymentMethod);
                return View("PreviewAndPay", viewModel);
            }

            return RedirectToAction("ThankYou");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult DeliveryDetails(DeliveryDetailsViewModel model)
        {
            // Check the selected shipping option
            bool isShippingNeeded = mShoppingService.GetCurrentShoppingCart().IsShippingNeeded;
            if (isShippingNeeded && !mCheckoutService.IsShippingOptionValid(model.ShippingOption.ShippingOptionID))
            {
                ModelState.AddModelError("ShippingOption.ShippingOptionID", ResHelper.GetString("DancingGoatMvc.Shipping.ShippingOptionRequired"));
            }

            // Check if the billing address's country and state are valid
            var countryStateViewModel = model.BillingAddress.BillingAddressCountryStateSelector;
            if (!mCheckoutService.IsCountryValid(countryStateViewModel.CountryID))
            {
                countryStateViewModel.CountryID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.CountryID", ResHelper.GetString("DancingGoatMvc.Address.CountryIsRequired"));
            }
            else if (!mCheckoutService.IsStateValid(countryStateViewModel.CountryID, countryStateViewModel.StateID))
            {
                countryStateViewModel.StateID = 0;
                ModelState.AddModelError("BillingAddress.BillingAddressCountryStateSelector.StateID", ResHelper.GetString("DancingGoatMvc.Address.StateIsRequired"));
            }

            if (!ModelState.IsValid)
            {
                var viewModel = mCheckoutService.PrepareDeliveryDetailsViewModel(model.Customer, model.BillingAddress, model.ShippingOption);

                return View(viewModel);
            }

            var customer = GetCustomerOrCreateFromAuthenticatedUser() ?? new CustomerInfo();
            bool emailCanBeChanged = !User.Identity.IsAuthenticated || string.IsNullOrWhiteSpace(customer.CustomerEmail);
            model.Customer.ApplyToCustomer(customer, emailCanBeChanged);
            mShoppingService.SetCustomer(customer);

            var modelAddressID = model.BillingAddress.BillingAddressSelector?.AddressID ?? 0;
            var billingAddress = mCheckoutService.GetAddress(modelAddressID) ?? new AddressInfo();

            model.BillingAddress.ApplyTo(billingAddress);
            billingAddress.AddressPersonalName = $"{customer.CustomerFirstName} {customer.CustomerLastName}";

            mShoppingService.SetBillingAddress(billingAddress);
            mShoppingService.SetShippingOption(model.ShippingOption?.ShippingOptionID ?? 0);

            return RedirectToAction("PreviewAndPay");
        }


        public ActionResult ThankYou()
        {
            var companyContact = mContactRepository.GetCompanyContact();

            var viewModel = new ThankYouViewModel
            {
                Phone = companyContact.Phone
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult AddItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                mShoppingService.AddItemToCart(item.SKUID, item.Units);
            }

            return RedirectToAction("ShoppingCart");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult UpdateItem(CartItemUpdateModel item)
        {
            if (ModelState.IsValid)
            {
                mShoppingService.UpdateItemQuantity(item.ID, item.Units);
            }
            else
            {
                // Add an item error and save ViewData so that the ShoppingCart action can show validation errors
                var key = item.ID.ToString();
                ModelState.Add(key, ModelState["Units"]);
            }

            var cartViewModel = mCheckoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult RemoveItem(CartItemUpdateModel item)
        {
            mShoppingService.RemoveItemFromCart(item.ID);

            var cartViewModel = mCheckoutService.PrepareCartViewModel();
            return View("ShoppingCart", cartViewModel);
        }


        [HttpPost]
        public JsonResult CustomerAddress(int addressID)
        {
            var address = mCheckoutService.GetCustomerAddress(addressID); 

            if (address == null)
            {
                return null;
            }

            var responseModel = new
            {
                Line1 = address.AddressLine1,
                Line2 = address.AddressLine2,
                City = address.AddressCity,
                PostalCode = address.AddressZip,
                CountryID = address.AddressCountryID,
                StateID = address.AddressStateID,
                PersonalName = address.AddressPersonalName
            };

            return Json(responseModel);
        }


        public ActionResult ItemDetail(int skuId)
        {
            var product = mProductRepository.GetProductForSKU(skuId);

DancingGoatMvc/Controllers/CoffeesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using CMS.Core;
using CMS.Ecommerce;

using DancingGoat.Models.Coffees;
using DancingGoat.Models.Products;
using DancingGoat.Repositories;
using DancingGoat.Repositories.Filters;
using DancingGoat.Services;

namespace DancingGoat.Controllers
{
    public class CoffeesController : Controller
    {
        private readonly ICoffeeRepository mCoffeeRepository;
        private readonly ICalculationService mCalculationService;


        public CoffeesController(ICoffeeRepository coffeeRepository, ICalculationService calculationService)
        {
            mCoffeeRepository = coffeeRepository;
            mCalculationService = calculationService;
        }


        // GET: Coffees
        public ActionResult Index()
        {
            var items = GetFilteredCoffees(null);
            var filter = new CoffeeFilterViewModel();
            filter.Load();

            return View(new ProductListViewModel
            {
                Filter = filter,
                Items = items
            });
        }


        // POST: Filter
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Filter(CoffeeFilterViewModel filter)
        {
            if (!Request.IsAjaxRequest())
            {
                return HttpNotFound();
            }
               
            var items = GetFilteredCoffees(filter);

            return PartialView("CoffeeList", items);
        }


        private IEnumerable<ProductListItemViewModel> GetFilteredCoffees(IRepositoryFilter filter)
        {
            var coffees = mCoffeeRepository.GetCoffees(filter);
           
            var items = coffees.Select(
                coffee => new ProductListItemViewModel(
                    coffee,
                    mCalculationService.CalculatePrice(coffee.SKU),
                    coffee.Product.PublicStatus?.PublicStatusDisplayName));
            return items;
        }
    }
}

DancingGoatMvc/Controllers/CouponController.cs
using System.Web.Mvc;

using CMS.Ecommerce;
using CMS.Helpers;

using DancingGoat.ActionSelectors;
using DancingGoat.Models.Checkout;
using DancingGoat.Services;

namespace DancingGoat.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly IShoppingService mShoppingService;
        private readonly ICheckoutService mCheckoutService;


        public CouponController(IShoppingService shoppingService, ICheckoutService checkoutService)
        {
            mShoppingService = shoppingService;
            mCheckoutService = checkoutService;
        }


        // GET: Coupon/Show
        public ActionResult Show()
        {
            var viewModel = mCheckoutService.PrepareCartViewModel();

            return PartialView("_CouponCodeEdit", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult AddCouponCode(CouponCodesUpdateModel model)
        {
            string couponCode = model.NewCouponCode?.Trim();
            if (string.IsNullOrEmpty(couponCode) || !mShoppingService.AddCouponCode(couponCode))
            {
                return new JsonResult
                {
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    Data = new { CouponCodeInvalidMessage = ResHelper.GetString("DancingGoatMvc.Checkout.CouponCodeInvalid") }
                };

            }

            return new EmptyResult();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ButtonNameAction]
        [ValidateInput(false)]
        public ActionResult RemoveCouponCode(CouponCodesUpdateModel model)
        {
            mShoppingService.RemoveCouponCode(model.RemoveCouponCode);

            return new EmptyResult();
        }
    }
}

DancingGoatMvc/Views/Checkout/DeliveryDetails.cshtml
@model DancingGoat.Models.Checkout.DeliveryDetailsViewModel

@{
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.Checkout.CustomerDetails");
}

<div class="checkout-container">
    <div class="container cart">
        <div class="checkout-back-link">
            <a href="@Url.Action("ShoppingCart")">&larr; @ResHelper.GetString("DancingGoatMvc.Checkout.BackToShoppingCart")</a>
        </div>

        @using (Html.BeginForm("DeliveryDetails", "Checkout", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-md-4">
                    <div class="customer-details">
                        <div class="form-horizontal">
                            @Html.EditorFor(m => m.Customer)
                            @Html.EditorFor(m => m.BillingAddress)
                            @if (Model.ShippingOption.IsVisible)
                            {
                                @Html.EditorFor(m => m.ShippingOption)
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-md-offset-4">

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <h2>@ResHelper.GetString("DancingGoatMvc.DeliveryDetails.AlreadyCustomer")</h2>
                        <p>@ResHelper.GetString("DancingGoatMvc.DeliveryDetails.AccessDetails")</p>
                        @Html.ActionLink(ResHelper.GetString("DancingGoatMvc.DeliveryDetails.SignIn"), "Login", "Account", new { returnUrl = Server.UrlEncode(Request.RawUrl) }, new { @class = "btn btn-secondary btn-default" })
                    }

                    <div class="gray-box floating-box">
                        <p>@ResHelper.GetString("DancingGoatMvc.Checkout.FillDetailsAndProceed")</p>
                        <input type="submit" class="btn btn-primary btn-default checkout-button" value="@ResHelper.GetString("DancingGoatMvc.Checkout.ReviewOrder")" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/countryStateSelector.js")
    @Scripts.Render("~/Scripts/addressSelector.js")
}

DancingGoatMvc/Views/Checkout/PreviewAndPay.cshtml
@model DancingGoat.Models.Checkout.PreviewViewModel

@{
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.Checkout.ShoppingCartPreview");
}

<div class="checkout-container">
    <div class="cart">
        <div class="continue-shopping-link">
            <a href="@Url.Action("DeliveryDetails")">&larr; @ResHelper.GetString("DancingGoatMvc.Checkout.BackToCustomerDetails")</a>
        </div>

        @Html.ValidationSummary(true, ResHelper.GetString("DancingGoatMvc.Checkout.OrderFailed"), new { @class = "ErrorLabel red" })
        <div>
            @Html.ValidationMessage("shipping", new { @class = "red" })
        </div>
        <div>
            @Html.ValidationMessage("cart.empty", new { @class = "red" })
        </div>

        <div class="col-md-8 cart-content">
            <div class="row">
                <div class="col-md-6">
                    <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.BillingDetails")</h2>

                    @Html.DisplayFor(m => m.CustomerDetails)

                    <br />

                    @Html.DisplayFor(m => m.BillingAddress)
                </div>
                @if (Model.DeliveryDetails.ShippingOption.IsVisible)
                {
                    <div class="col-md-6">
                        <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.ShippingDetails")</h2>
                        <span>@Model.ShippingName</span>
                        <br />
                        <div>@Model.CustomerDetails.Company</div>

                        <br />

                        @Html.DisplayFor(m => m.BillingAddress)
                    </div>
                }
            </div>
            <div class="row">
                <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.OrderedItems")</h2>
                <hr class="first-separator" />

                @Html.Partial("_ShoppingCartContentPreview", Model.CartModel)
            </div>
        </div>
        <div class="col-md-4">
            <div class="cart-right-panel floating-box">
                <div id="shoppingCartTotals">
                    @Html.Partial("_ShoppingCartTotals", Model.CartModel)
                </div>

                @using (Html.BeginForm("PreviewAndPay", "Checkout", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.EditorFor(m => m.PaymentMethod)
                    <input type="submit" value="@ResHelper.GetString("DancingGoatMvc.Checkout.ConfirmAndPayButton")" class="btn-primary checkout-button btn btn-default" />
                }
            </div>
        </div>
    </div>
</div>

DancingGoatMvc/Views/Checkout/ShoppingCart.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@section Scripts{
    <script type="text/javascript">$('#couponCode').load('@Url.Action("Show", "Coupon")')</script>
}

@{
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.ShoppingCart");
}

<div class="checkout-container">
    <div class="cart">
        <div class="continue-shopping-link">
            <a href="@Url.Action("Index", "Coffees")">&larr; @ResHelper.GetString("DancingGoatMvc.Checkout.ContinueShopping")</a>
        </div>

        @if (!ViewData.ModelState.IsValid)
        {
            @Html.ValidationSummary(null, new { @class = "invalid-cart-content" })
        }

        <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.YourShoppingCart")</h2>
        <div class="col-md-8 cart-content">
            <hr class="first-separator" />
            @if (Model.IsEmpty)
            {
                <span>@ResHelper.GetString("DancingGoatMvc.Checkout.ShoppingCartIsEmpty")</span>
                <hr class="last-separator" />
            }
            else
            {
                @Html.Partial("_ShoppingCartContentEdit", Model)
            }

            @if (Model.RemainingAmountForFreeShipping > 0)
            {
                <section class="free-shipping-promotion">
                    <div>
                        <span>
                            @ResHelper.GetStringFormat("DancingGoatMvc.ShoppingCart.FreeDelivery", Model.FormatPrice(Model.RemainingAmountForFreeShipping))
                        </span>
                    </div>
                </section>
            }
        </div>
        <div class="col-md-4">
            <div class="cart-right-panel floating-box">
                <div id="couponCode"></div>
                <hr>

                @using (Html.BeginForm("ShoppingCart", "Checkout", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    @Html.Partial("_ShoppingCartTotals", Model)

                    <p>@ResHelper.GetString("DancingGoatMvc.Checkout.ReviewAndCheckout")</p>

                    <input type="submit" name="ShoppingCartCheckout" value="@ResHelper.GetString("DancingGoatMvc.Checkout")" class="btn-primary checkout-button btn btn-default" />
                }
            </div>
        </div>
    </div>
</div>

DancingGoatMvc/Views/Checkout/ThankYou.cshtml
@model DancingGoat.Models.Checkout.ThankYouViewModel

@{ 
    ViewBag.Title = ResHelper.GetString("DancingGoatMvc.Checkout.ThankYou");
}

<div class="col-md-6 col-lg-5">
    <div class="thank-you-content">
        <h2>@ResHelper.GetString("DancingGoatMvc.Checkout.ThankYou")</h2>

        <p>@ResHelper.GetString("DancingGoatMvc.Order.Success")</p>
        <p>@Html.Raw(ResHelper.GetStringFormat("DancingGoatMvc.Order.Questions", Model.Phone))</p>
    </div>
</div>

DancingGoatMvc/Views/Checkout/_ShoppingCartContentEdit.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@foreach (var cartItem in Model.CartItems)
{
    <div class="row">
        <div class="col-md-10">
            <div class="cart-item-image">
                <a href="@Url.Action("ItemDetail", new { skuId = cartItem.SKUID })">
                    @Html.Image(@cartItem.SKUImagePath, @cartItem.SKUName, null, SizeConstraint.MaxWidthOrHeight(70))
                </a>
            </div>
            <div class="cart-item-info">
                @Html.ActionLink(cartItem.SKUName, "ItemDetail", new { skuId = cartItem.SKUID })
            </div>
            @using (Html.BeginForm("ShoppingCart", "Checkout", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="cart-item-amount">
                    <span>Qty</span>
                    <input type="hidden" name="ID" value="@cartItem.CartItemID" />
                    <input type="text" name="Units" value="@cartItem.CartItemUnits" class="form-control" />
                    <input type="submit" name="UpdateItem" value="@ResHelper.GetString("DancingGoatMvc.ShoppingCart.Update")" class="btn btn-default" />
                    <input type="submit" name="RemoveItem" value="@ResHelper.GetString("DancingGoatMvc.ShoppingCart.Remove")" class="btn btn-default" />
                </div>
            }
            @Html.ValidationMessage(cartItem.CartItemID.ToString(), new { @class = "red"})
        </div>
        <div class="col-md-2 cart-item-subtotal">
            <span>@Model.FormatPrice(cartItem.TotalPrice)</span>
        </div>
    </div>
    <hr />
}

DancingGoatMvc/Views/Checkout/_ShoppingCartContentPreview.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@foreach (var cartItem in Model.CartItems)
{
    <div class="row">
        <div class="col-md-10">
            <div class="cart-item-image">
                <a href="@Url.Action("ItemDetail", new { skuId = cartItem.SKUID })">
                    @Html.Image(@cartItem.SKUImagePath, @cartItem.SKUName, null, SizeConstraint.MaxWidthOrHeight(70))
                </a>
            </div>
            <div class="cart-item-info">
                @Html.ActionLink(cartItem.SKUName, "ItemDetail", new { skuId = cartItem.SKUID })
            </div>
            <div class="cart-item-amount">
                <span>Qty</span>
                <input type="text" name="Units" value="@cartItem.CartItemUnits" class="form-control" disabled />
            </div>

            @Html.ValidationMessage(cartItem.CartItemID.ToString(), new { @class = "red" })

        </div>
        <div class="col-md-2 cart-item-subtotal">
            <span>@Model.FormatPrice(cartItem.TotalPrice)</span>
        </div>
    </div>
    <hr />
}

DancingGoatMvc/Views/Checkout/_ShoppingCartTotals.cshtml
@model DancingGoat.Models.Checkout.CartViewModel

@{
    var tax = Model.TotalTax;
    var shipping = Model.TotalShipping;
}

@if (tax > 0)
{
    <div class="cart-total-viewer">
        <div class="label">
            @ResHelper.GetString("DancingGoatMvc.ShoppingCart.TotalTax")
        </div>
        <div class="value">
            @Model.FormatPrice(tax)
        </div>
    </div>
}

@if (shipping > 0)
{
    <div class="cart-total-viewer">
        <div class="label">
            @ResHelper.GetString("DancingGoatMvc.ShoppingCart.Shipping")
        </div>
        <div class="value">
            @Model.FormatPrice(shipping)
        </div>
    </div>
}


@if ((tax > 0) || (shipping > 0))
{
    <hr />
}

<div class="cart-total">
    <div class="cart-total-viewer">
        <div class="label">
            <span>@ResHelper.GetString("DancingGoatMvc.ShoppingCart.Total")</span>
        </div>
        <div class="value">
            <span>@Model.FormatPrice(Model.GrandTotal)</span>
        </div>
    </div>
</div>